# Dependencies
highlighter: rouge

# Permalinks
permalink: /:year/:month/:title/
paginate_path: "/blog/page:num/"

# Setup
title: 'Thomas Alisi'
tagline: 'specialization is for insects'
description: 'Fast learner, PhD, Tech Lead, Developer, job titles disliker. Entrepreneurial kind.'
baseurl: '/'

# sitemap
url: https://tom.londondroids.com

author:
  name: 'Thomas Alisi'

paginate: 3

github:
  repo: https://github.com/grudelsud/grudelsud.github.io

encoding: utf-8

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
