# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:title/
# relative_permalinks: true
paginate_path: "/blog/page:num/"

# Setup
title:            'Tom Alisi'
tagline:          'specialization is for insects'
description:      'Fast learner and job titles disliker. Roughly: Entrepreneur, PhD, Solutions Architect, Developer'
url:              http://tom.londondroids.com
baseurl:          /

author:
  name:           'Thomas M. Alisi'
  url:            https://twitter.com/grudelsud

paginate:         3

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/grudelsud/grudelsud.github.io

encoding:         utf-8

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
