# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title/
relative_permalinks: true

# Setup
title:            'Thomas M. Alisi'
tagline:          'home of grudelsud'
description:      'putting together what I have done along few years, mostly for work and overnight'
url:              http://grudelsud.github.io
baseurl:          /

author:
  name:           'Thomas M. Alisi'
  url:            https://twitter.com/grudelsud

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/grudelsud/grudelsud.github.io

encoding:         utf-8