# Dependencies
highlighter: rouge

# Permalinks
permalink: /:year/:month/:title/
paginate_path: "/blog/page:num/"

# Setup
title: 'Tom Alisi'
tagline: 'specialization is for insects'
description: 'Fast learner and job titles disliker. Roughly: Entrepreneur, PhD, Solutions Architect, Developer'
baseurl: http://tom.londondroids.com

author:
  name: 'Tom Alisi'

paginate: 3

github:
  repo: https://github.com/grudelsud/grudelsud.github.io

encoding: utf-8

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
